### ISSUE TITLE
Labels are layed out incorrectly when there are no buttons in 2.0 branch

### ISSUE THREAD

**Issue by MaxHasADHD** [LeoNatan/LNPopupController#107]
Is there any reason you are not using Autolayout with LNPopupBar? I'm finding the layout not working well. So far I have set a image and a title and subtitle, and the titles were off to the side. I fixed by making the value absolute but the width is pretty small. I think by having 3 views, the left view, right view, and titles center view, then the titles could stretch between the left and right views automatically with auto layout. 

Edit:
So to fix the layout issues, besides making the titlesView width absolute, I check if firstRightItemView is nil. If so I subtract 10 for the margin.

**Comment by LeoNatan** [comment]
I am sorry, I have no idea what you just said. Post a screenshot of where you are seeing an issue. If you are using 2.0 branch, notice that the entire layout has changed, and labels are now aligned to the left, and there is no marquee scroll by default. What has autolayout to do with anything here?

**Comment by MaxHasADHD** [comment]
I set the image, title, and subtitle and this is how it naturally lays out with the 2.0 branch. I am not setting a right view which appears to the the issue with the layout. I'm asking why you aren't using Auto-layout because the layout isn't particularly hard and can be easily set with constraints instead of figuring out all of the insets and center for everything. Would likely be less code.


![screen shot 2016-10-30 at 4 46 24 pm](https://cloud.githubusercontent.com/assets/1296190/19841024/7062728c-9ec0-11e6-984a-f6e8c74e15b4.png)

**Comment by LeoNatan** [comment]
I will test. I cannot use AutoLayout here because have to have precise control over frames. I will take a look at this issue. Thanks for checking out 2.0 branch and reporting!

**Comment by LeoNatan** [comment]
For now, I suggest using the stable branch. 2.0 is work in progress as you can see.

**Comment by LeoNatan** [comment]
Fixed this issue in 2.0 branch. Please confirm.

**Comment by LeoNatan** [comment]
BTW, cool app! Always nice to see success stories. What app is it? Is it out on the store already?

**Comment by codemonza** [comment]
Hi Leo, thank you for all your hard work! I am seeing this same problem. However the first didSelectRowAt call does not have this problem. It's only if a second row is selected, the problem persists afterwards. Please let me know how I could help you debug this. Thanks!

**Comment by LeoNatan** [comment]
Please open a new issue. Thanks
