### ISSUE TITLE
Constraint warnings on `contentViewController`

### ISSUE THREAD

**Issue by DantePuglisi** [LeoNatan/LNPopupController#398]
#### Description
Lots of constraints warnings on the `contentViewController` when doing `presentPopupBar(withContentViewController:animated:completion:)`. As soon as the `popupBar` appears the console gets filled with warnings. If I present this same `UIViewController` in any other way there are no constraint issues. I built the UI of my `contentViewController` in a `.xib`

#### Log
```
2020-08-18 22:21:44.786131-0300 Project[77937:2390184] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x60000321f200 h=-&- v=-&- UIView:0x7f915b663bd0.minX == 0   (active, names: '|':Project.EnergyTimeView:0x7f915b663330 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x60000321f250 h=-&- v=-&- H:[UIView:0x7f915b663bd0]-(0)-|   (active, names: '|':Project.EnergyTimeView:0x7f915b663330 )>",
    "<NSLayoutConstraint:0x6000032e3160 H:[UIStackView:0x7f915b663eb0]-(20)-|   (active, names: '|':UIView:0x7f915b663d40 )>",
    "<NSLayoutConstraint:0x6000032e31b0 H:|-(20)-[UIStackView:0x7f915b663eb0]   (active, names: '|':UIView:0x7f915b663d40 )>",
    "<NSLayoutConstraint:0x6000032e32a0 H:|-(0)-[UIView:0x7f915b663d40]   (active, names: '|':UIView:0x7f915b663bd0 )>",
    "<NSLayoutConstraint:0x6000032e3340 UILayoutGuide:0x600002803020'UIViewSafeAreaLayoutGuide'.trailing == UIView:0x7f915b663d40.trailing   (active)>",
    "<NSLayoutConstraint:0x6000032e3980 H:|-(0)-[Project.EnergyTimeView:0x7f915b663330]   (active, names: '|':UIView:0x7f915b608e10 )>",
    "<NSLayoutConstraint:0x6000032e3a20 H:[Project.EnergyTimeView:0x7f915b663330]-(0)-|   (active, names: '|':UIView:0x7f915b608e10 )>",
    "<NSLayoutConstraint:0x600003200910 UIView:0x7f915b608e10.width == UIView:0x7f915b667f80.width   (active)>",
    "<NSLayoutConstraint:0x60000321ef30 'UISV-canvas-connection' UIStackView:0x7f915b663eb0.leading == UIView:0x7f915b664040.leading   (active)>",
    "<NSLayoutConstraint:0x60000321ef80 'UISV-canvas-connection' H:[UIView:0x7f915b665060]-(0)-|   (active, names: '|':UIStackView:0x7f915b663eb0 )>",
    "<NSLayoutConstraint:0x60000321f020 'UISV-fill-equally' UIView:0x7f915b665060.width == UIView:0x7f915b664040.width   (active)>",
    "<NSLayoutConstraint:0x60000321efd0 'UISV-spacing' H:[UIView:0x7f915b664040]-(15)-[UIView:0x7f915b665060]   (active)>",
    "<NSLayoutConstraint:0x60000321f340 'UIView-Encapsulated-Layout-Width' UIView:0x7f915b667f80.width == 0   (active)>",
    "<NSLayoutConstraint:0x6000032e3480 'UIViewSafeAreaLayoutGuide-right' H:[UILayoutGuide:0x600002803020'UIViewSafeAreaLayoutGuide']-(0)-|(LTR)   (active, names: '|':UIView:0x7f915b663bd0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000321efd0 'UISV-spacing' H:[UIView:0x7f915b664040]-(15)-[UIView:0x7f915b665060]   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-18 22:21:44.787056-0300 Project[77937:2390184] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000032e13b0 Project.CircleView:0x7f915b62dcb0.width == Project.CircleView:0x7f915b62dcb0.height   (active)>",
    "<NSLayoutConstraint:0x6000032e3890 H:[Project.CircleView:0x7f915b62dcb0]-(20)-|   (active, names: '|':UIView:0x7f915b608e10 )>",
    "<NSLayoutConstraint:0x6000032e38e0 H:|-(20)-[Project.CircleView:0x7f915b62dcb0]   (active, names: '|':UIView:0x7f915b608e10 )>",
    "<NSLayoutConstraint:0x600003200910 UIView:0x7f915b608e10.width == UIView:0x7f915b667f80.width   (active)>",
    "<NSLayoutConstraint:0x60000321f340 'UIView-Encapsulated-Layout-Width' UIView:0x7f915b667f80.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000032e13b0 Project.CircleView:0x7f915b62dcb0.width == Project.CircleView:0x7f915b62dcb0.height   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-18 22:21:44.787585-0300 Project[77937:2390184] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000032e37f0 UIView:0x7f915b615380.trailing == Project.CircleView:0x7f915b62dcb0.trailing   (active)>",
    "<NSLayoutConstraint:0x6000032e3840 UIView:0x7f915b615380.leading == Project.CircleView:0x7f915b62dcb0.leading   (active)>",
    "<NSLayoutConstraint:0x6000032e3890 H:[Project.CircleView:0x7f915b62dcb0]-(20)-|   (active, names: '|':UIView:0x7f915b608e10 )>",
    "<NSLayoutConstraint:0x6000032e38e0 H:|-(20)-[Project.CircleView:0x7f915b62dcb0]   (active, names: '|':UIView:0x7f915b608e10 )>",
    "<NSLayoutConstraint:0x600003200910 UIView:0x7f915b608e10.width == UIView:0x7f915b667f80.width   (active)>",
    "<NSLayoutConstraint:0x60000321f340 'UIView-Encapsulated-Layout-Width' UIView:0x7f915b667f80.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000032e37f0 UIView:0x7f915b615380.trailing == Project.CircleView:0x7f915b62dcb0.trailing   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-18 22:21:44.788267-0300 Project[77937:2390184] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x60000321f200 h=-&- v=-&- UIView:0x7f915b663bd0.minX == 0   (active, names: '|':Project.EnergyTimeView:0x7f915b663330 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x60000321f250 h=-&- v=-&- H:[UIView:0x7f915b663bd0]-(0)-|   (active, names: '|':Project.EnergyTimeView:0x7f915b663330 )>",
    "<NSLayoutConstraint:0x6000032e3160 H:[UIStackView:0x7f915b663eb0]-(20)-|   (active, names: '|':UIView:0x7f915b663d40 )>",
    "<NSLayoutConstraint:0x6000032e31b0 H:|-(20)-[UIStackView:0x7f915b663eb0]   (active, names: '|':UIView:0x7f915b663d40 )>",
    "<NSLayoutConstraint:0x6000032e32a0 H:|-(0)-[UIView:0x7f915b663d40]   (active, names: '|':UIView:0x7f915b663bd0 )>",
    "<NSLayoutConstraint:0x6000032e3340 UILayoutGuide:0x600002803020'UIViewSafeAreaLayoutGuide'.trailing == UIView:0x7f915b663d40.trailing   (active)>",
    "<NSLayoutConstraint:0x6000032e3980 H:|-(0)-[Project.EnergyTimeView:0x7f915b663330]   (active, names: '|':UIView:0x7f915b608e10 )>",
    "<NSLayoutConstraint:0x6000032e3a20 H:[Project.EnergyTimeView:0x7f915b663330]-(0)-|   (active, names: '|':UIView:0x7f915b608e10 )>",
    "<NSLayoutConstraint:0x600003200910 UIView:0x7f915b608e10.width == UIView:0x7f915b667f80.width   (active)>",
    "<NSLayoutConstraint:0x60000321f340 'UIView-Encapsulated-Layout-Width' UIView:0x7f915b667f80.width == 0   (active)>",
    "<NSLayoutConstraint:0x6000032e3480 'UIViewSafeAreaLayoutGuide-right' H:[UILayoutGuide:0x600002803020'UIViewSafeAreaLayoutGuide']-(0)-|(LTR)   (active, names: '|':UIView:0x7f915b663bd0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000032e3160 H:[UIStackView:0x7f915b663eb0]-(20)-|   (active, names: '|':UIView:0x7f915b663d40 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-18 22:21:44.788990-0300 Project[77937:2390184] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000032e3890 H:[Project.CircleView:0x7f915b62dcb0]-(20)-|   (active, names: '|':UIView:0x7f915b608e10 )>",
    "<NSLayoutConstraint:0x6000032e38e0 H:|-(20)-[Project.CircleView:0x7f915b62dcb0]   (active, names: '|':UIView:0x7f915b608e10 )>",
    "<NSLayoutConstraint:0x600003200910 UIView:0x7f915b608e10.width == UIView:0x7f915b667f80.width   (active)>",
    "<NSLayoutConstraint:0x60000321f340 'UIView-Encapsulated-Layout-Width' UIView:0x7f915b667f80.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000032e3890 H:[Project.CircleView:0x7f915b62dcb0]-(20)-|   (active, names: '|':UIView:0x7f915b608e10 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-18 22:21:44.789355-0300 Project[77937:2390184] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600003200960 Project.CircleView:0x7f915b62dcb0.width == UIView:0x7f915b667f80.width - 40   (active)>",
    "<NSLayoutConstraint:0x60000321f340 'UIView-Encapsulated-Layout-Width' UIView:0x7f915b667f80.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600003200960 Project.CircleView:0x7f915b62dcb0.width == UIView:0x7f915b667f80.width - 40   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-18 22:21:44.789915-0300 Project[77937:2390184] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000032000a0 UIView:0x7f915b668260.height == 1   (active)>",
    "<NSLayoutConstraint:0x600003200280 UIView:0x7f915b668260.top == UIView:0x7f915b6680f0.topMargin + 60   (active)>",
    "<NSLayoutConstraint:0x600003200320 V:[UIView:0x7f915b668260]-(0)-[UIScrollView:0x7f915c079400]   (active)>",
    "<NSLayoutConstraint:0x600003200410 V:[UIScrollView:0x7f915c079400]-(0)-|   (active, names: '|':UIView:0x7f915b6680f0 )>",
    "<NSLayoutConstraint:0x600003200640 V:|-(0)-[UIView:0x7f915b6680f0]   (active, names: '|':UIView:0x7f915b667f80 )>",
    "<NSLayoutConstraint:0x600003200690 V:[UIView:0x7f915b6680f0]-(0)-|   (active, names: '|':UIView:0x7f915b667f80 )>",
    "<NSLayoutConstraint:0x60000321f390 'UIView-Encapsulated-Layout-Height' UIView:0x7f915b667f80.height == 0   (active)>",
    "<NSLayoutConstraint:0x600003200500 'UIView-topMargin-guide-constraint' V:|-(8)-[UILayoutGuide:0x600002803640'UIViewLayoutMarginsGuide']   (active, names: '|':UIView:0x7f915b6680f0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000032000a0 UIView:0x7f915b668260.height == 1   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-18 22:21:44.790422-0300 Project[77937:2390184] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600003200280 UIView:0x7f915b668260.top == UIView:0x7f915b6680f0.topMargin + 60   (active)>",
    "<NSLayoutConstraint:0x600003200320 V:[UIView:0x7f915b668260]-(0)-[UIScrollView:0x7f915c079400]   (active)>",
    "<NSLayoutConstraint:0x600003200410 V:[UIScrollView:0x7f915c079400]-(0)-|   (active, names: '|':UIView:0x7f915b6680f0 )>",
    "<NSLayoutConstraint:0x600003200640 V:|-(0)-[UIView:0x7f915b6680f0]   (active, names: '|':UIView:0x7f915b667f80 )>",
    "<NSLayoutConstraint:0x600003200690 V:[UIView:0x7f915b6680f0]-(0)-|   (active, names: '|':UIView:0x7f915b667f80 )>",
    "<NSLayoutConstraint:0x60000321f390 'UIView-Encapsulated-Layout-Height' UIView:0x7f915b667f80.height == 0   (active)>",
    "<NSLayoutConstraint:0x600003200500 'UIView-topMargin-guide-constraint' V:|-(8)-[UILayoutGuide:0x600002803640'UIViewLayoutMarginsGuide']   (active, names: '|':UIView:0x7f915b6680f0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600003200320 V:[UIView:0x7f915b668260]-(0)-[UIScrollView:0x7f915c079400]   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

#### Device, OS and Xcode Versions
Xcode 11.6
Simulator with iOS 13.6 (iPhone 11 Pro and iPhone 11 Pro Max)

**Comment by LeoNatan** [comment]
Hello,

Are you seeing this with the latest 2.10.1? I just fixed this today.

**Comment by DantePuglisi** [comment]
I was on `2.10.0`, just updated and still getting errors but only on vertical (and height) constraints 🤔

**Comment by LeoNatan** [comment]
Hmm
Can you please provide a small demo project, reproducing this?

**Comment by iDevelopper** [comment]
@LeoNatan ,

@DantePuglisi removed the small demo project he uploaded a few days ago. I still have it and I have tested it with version 2.10.1. I did not see any issues.

**Comment by LeoNatan** [comment]
@iDevelopper What demo project? You mean the one provided here: https://github.com/LeoNatan/LNPopupController/issues/396#issuecomment-674380206 ? If so, I already fixed an issue there. But here it must be something else.

**Comment by iDevelopper** [comment]
Oups! I confused the two issues, sorry!

**Comment by DantePuglisi** [comment]
I will try to create a small demo project to reproduce this in the following days, sorry for the delay!

**Comment by LeoNatan** [comment]
Thank you!

**Comment by DantePuglisi** [comment]
I could put together a small project to reproduce. I think it might have something to do with the horizontal `UIScrollView`. At the same time I couldn't find any way to let the user swipe-down-to-dismiss while allowing horizontal scrolling for the `UIScrollView`, swipe down only works while scrolling the `UIScrollView` (which is something I'd like to prevent as well).

Thanks for taking the time and let me know if you need anything else!

[TestPopupController.zip](https://github.com/LeoNatan/LNPopupController/files/5098891/TestPopupController.zip)

**Comment by LeoNatan** [comment]
I might have found the cause. In one place, the frame of the view is set to (0,0,0,0), which can confuse the layout system. I'll test on your demo project to see during the weekend.

**Comment by DantePuglisi** [comment]
@LeoNatan there's no way I can make pull down work when the content of the ViewController is a horizontal `UIScrollView`, it's reflected in the `TestPopupController.zip` I sent. Is there any chance you can take a quick look there? I've tried all you proposed on the other questions but nothing seems to work appropriately.

**Comment by LeoNatan** [comment]
There is an issue open about this from several years ago. You might need to play around with the interaction gesture recognizer's delegate to allow the interaction if the pan is horizontal, rather than vertical.

**Comment by DantePuglisi** [comment]
Trust me I spent a day trying to figure it out with no luck, maybe the OS changed in regards to how this is handled since several years ago?
