### ISSUE TITLE
PopupView moving under Status Bar

### ISSUE THREAD

**Issue by ClapCharts** [LeoNatan/LNPopupController#74]
I have got a new issue that is similar to issues #41 and #52 except that I don't use a navigation controller in my app.

The popup appears correctly on creation, with status bar sitting on top. However, if the UI is updated, the popup moves downward, below the status bar. 

I have updated the sample project I did for issue #71 to demonstrate this as well : https://github.com/ClapCharts/TestProject.git

Thanks again!

**Comment by LeoNatan** [comment]
@ClapCharts Can you see if this issue reproduces for you with branch 2_0?

**Comment by ClapCharts** [comment]
Yes. However, I've noticed that it happens it I set a vertical constraint to top layout guide for the image but it works fine if I set a vertical constraint to bottom layout.

**Comment by LeoNatan** [comment]
How are you setting constraints. Could be that constraints are pulling the popup content view down. Could you post a screenshot?

**Comment by ClapCharts** [comment]
<img width="744" alt="capture d ecran 2016-10-24 a 14 07 17" src="https://cloud.githubusercontent.com/assets/16122434/19645086/4a424a54-99f3-11e6-8a86-b13a32c6f586.png">

Here you go.
Happy to help if I can as your player is great. However, as I was saying in my previous comment, I found an alternative way to make it work in my project and, also, I am not a professional developper and it's possible that I made a beginner mistake in this test project... If no one else faces this issue, it might not be worth spending time on it!

**Comment by LeoNatan** [comment]
Thanks for your effort. Since I am unable to reproduce, I am not sure how to tackle this problem. I will keep this issue open for now, let's see if more people are facing it. If you've found a workaround that works for you, that's great.

**Comment by DCDJ** [comment]
Just ran into this issue. Have the same constraints setup as the OP. 

It looks like if the content view has a constraint that ties it to the top layout guide (lets say 20px offset from the very top of the view), the popup doesn't seem to take that into account until you either force an interface update/call another controller up which triggers it to recalculate constraints once the view re-appears and add in the layout guide offset (or at least I *think* that's what is happening)

![layoutbug](https://cloud.githubusercontent.com/assets/3400414/20653140/f0c0636c-b4ff-11e6-80d9-a2995fe81c63.gif)

Constraints:

<img width="900" alt="screen shot 2016-11-28 at 00 17 02" src="https://cloud.githubusercontent.com/assets/3400414/20653147/0b6a94bc-b500-11e6-91bf-42482b379717.png">

**Comment by LeoNatan** [comment]
@DCDJ I will try to reproduce and find a solution. It seems like an incorrect inset management.

**Comment by DCDJ** [comment]
@LeoNatan Thank you, really appreciate it

**Comment by LeoNatan** [comment]
@DCDJ @ClapCharts Fixed in both `master` and `2_0` branches. Please test and let me know if it works.

**Comment by DCDJ** [comment]
@LeoNatan Didn't seem to fix the issue. However - my top "bar" isn't actually a UINavigationBar, it is just a UIView that looks like a nav bar (I'm using a TabBarController so adding a UINavigationBar to the top felt a bit weird)

HOWEVER - If I changed my constraint from "Top Layout Guide 0px" to "View 20px" so that it was 20px from the top (essentially the same as tying it to the Top Layout Guide ) - that fixed the issue. I think there is a problem with calculating constraints against the Top Layout Guide.

**Comment by LeoNatan** [comment]
From what I checked, the top layout guide is calculated correctly. Perhaps I only checked when there is a navigation controller. (Why aren't you using a navigation controller for this anyway regardless of this issue?)

**Comment by DCDJ** [comment]
@LeoNatan Good point - try without a navigation controller and see what sort of result you get. It never really occurred to me to use a navigation controller specifically for what I'm doing as the furthest you'll navigate to in my app is opening up a tab bar controller (as shown in the gif.)

 I'll give it a shot with a navigation controller and see if the issue is gone.

**Comment by DCDJ** [comment]
Using Navigation Bar: is still presenting me with the same issue:

![screen shot 2016-11-29 at 16 38 20](https://cloud.githubusercontent.com/assets/3400414/20718928/46be8598-b652-11e6-878c-039f753ce944.png)

Constraint is set to: "Top Layout Guide 0px"

**Comment by LeoNatan** [comment]
Navigation controller, not bar directly. Otherwise it's the same issue as your view.

**Comment by DCDJ** [comment]
Sorry, that was a typo. I did mean Navigation Controller.

**Comment by LeoNatan** [comment]
Why are you setting a constraints on the bar of the controller. This is wrong.

**Comment by DCDJ** [comment]
Constraints of the rest of my content - not the nav bar. Navigation controller is controlling all of that for me.

I have attached a very basic demo of my current setup. Please let me know if this is the correct/incorrect way to use this plugin.

[PopupTest.zip](https://github.com/LeoNatan/LNPopupController/files/619778/PopupTest.zip)

**Comment by LeoNatan** [comment]
Guys, please test with new fix.

**Comment by DCDJ** [comment]
@LeoNatan Fixed :)

**Comment by LeoNatan** [comment]
😎
